apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: # these are deployment labels
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
  # these are used to select the pod to create it's replicas
    matchLabels: 
      tier: frontend
      app: nginx
  # this is pod replicas' definition which are going to be generated
  template:
    metadata:
    # these labels belongs to replicas which are going to be generated
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cip
spec:
  selector:
    tier: frontend
    app: nginx 
  ports:
  - name: nginx-cip-port
    protocol: TCP
    port: 80 # this port number is belongs to this service
    targetPort: 80 # this is target containr's port
